// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/search_trends/v1/search_trends.proto

package searchtrendspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchTrendsService_GetTop_FullMethodName         = "/search_trends.v1.SearchTrendsService/GetTop"
	SearchTrendsService_AddStopWord_FullMethodName    = "/search_trends.v1.SearchTrendsService/AddStopWord"
	SearchTrendsService_RemoveStopWord_FullMethodName = "/search_trends.v1.SearchTrendsService/RemoveStopWord"
	SearchTrendsService_ListStopWords_FullMethodName  = "/search_trends.v1.SearchTrendsService/ListStopWords"
	SearchTrendsService_HealthCheck_FullMethodName    = "/search_trends.v1.SearchTrendsService/HealthCheck"
)

// SearchTrendsServiceClient is the client API for SearchTrendsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchTrendsServiceClient interface {
	GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error)
	AddStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error)
	RemoveStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error)
	ListStopWords(ctx context.Context, in *ListStopWordsRequest, opts ...grpc.CallOption) (*ListStopWordsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type searchTrendsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchTrendsServiceClient(cc grpc.ClientConnInterface) SearchTrendsServiceClient {
	return &searchTrendsServiceClient{cc}
}

func (c *searchTrendsServiceClient) GetTop(ctx context.Context, in *GetTopRequest, opts ...grpc.CallOption) (*GetTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopResponse)
	err := c.cc.Invoke(ctx, SearchTrendsService_GetTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchTrendsServiceClient) AddStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWordResponse)
	err := c.cc.Invoke(ctx, SearchTrendsService_AddStopWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchTrendsServiceClient) RemoveStopWord(ctx context.Context, in *StopWordRequest, opts ...grpc.CallOption) (*StopWordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWordResponse)
	err := c.cc.Invoke(ctx, SearchTrendsService_RemoveStopWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchTrendsServiceClient) ListStopWords(ctx context.Context, in *ListStopWordsRequest, opts ...grpc.CallOption) (*ListStopWordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStopWordsResponse)
	err := c.cc.Invoke(ctx, SearchTrendsService_ListStopWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchTrendsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SearchTrendsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchTrendsServiceServer is the server API for SearchTrendsService service.
// All implementations must embed UnimplementedSearchTrendsServiceServer
// for forward compatibility.
type SearchTrendsServiceServer interface {
	GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error)
	AddStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error)
	RemoveStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error)
	ListStopWords(context.Context, *ListStopWordsRequest) (*ListStopWordsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedSearchTrendsServiceServer()
}

// UnimplementedSearchTrendsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchTrendsServiceServer struct{}

func (UnimplementedSearchTrendsServiceServer) GetTop(context.Context, *GetTopRequest) (*GetTopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTop not implemented")
}
func (UnimplementedSearchTrendsServiceServer) AddStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStopWord not implemented")
}
func (UnimplementedSearchTrendsServiceServer) RemoveStopWord(context.Context, *StopWordRequest) (*StopWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveStopWord not implemented")
}
func (UnimplementedSearchTrendsServiceServer) ListStopWords(context.Context, *ListStopWordsRequest) (*ListStopWordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStopWords not implemented")
}
func (UnimplementedSearchTrendsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSearchTrendsServiceServer) mustEmbedUnimplementedSearchTrendsServiceServer() {}
func (UnimplementedSearchTrendsServiceServer) testEmbeddedByValue()                             {}

// UnsafeSearchTrendsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchTrendsServiceServer will
// result in compilation errors.
type UnsafeSearchTrendsServiceServer interface {
	mustEmbedUnimplementedSearchTrendsServiceServer()
}

func RegisterSearchTrendsServiceServer(s grpc.ServiceRegistrar, srv SearchTrendsServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchTrendsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchTrendsService_ServiceDesc, srv)
}

func _SearchTrendsService_GetTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTrendsServiceServer).GetTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchTrendsService_GetTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTrendsServiceServer).GetTop(ctx, req.(*GetTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchTrendsService_AddStopWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTrendsServiceServer).AddStopWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchTrendsService_AddStopWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTrendsServiceServer).AddStopWord(ctx, req.(*StopWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchTrendsService_RemoveStopWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTrendsServiceServer).RemoveStopWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchTrendsService_RemoveStopWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTrendsServiceServer).RemoveStopWord(ctx, req.(*StopWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchTrendsService_ListStopWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStopWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTrendsServiceServer).ListStopWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchTrendsService_ListStopWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTrendsServiceServer).ListStopWords(ctx, req.(*ListStopWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchTrendsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchTrendsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchTrendsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchTrendsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchTrendsService_ServiceDesc is the grpc.ServiceDesc for SearchTrendsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchTrendsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search_trends.v1.SearchTrendsService",
	HandlerType: (*SearchTrendsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTop",
			Handler:    _SearchTrendsService_GetTop_Handler,
		},
		{
			MethodName: "AddStopWord",
			Handler:    _SearchTrendsService_AddStopWord_Handler,
		},
		{
			MethodName: "RemoveStopWord",
			Handler:    _SearchTrendsService_RemoveStopWord_Handler,
		},
		{
			MethodName: "ListStopWords",
			Handler:    _SearchTrendsService_ListStopWords_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SearchTrendsService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search_trends/v1/search_trends.proto",
}
