// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proto/search_trends/v1/search_trends.proto

package searchtrendspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items         []*TopItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	WindowSeconds uint32                 `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
}

func (x *GetTopResponse) Reset() {
	*x = GetTopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopResponse) ProtoMessage() {}

func (x *GetTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopResponse.ProtoReflect.Descriptor instead.
func (*GetTopResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopResponse) GetItems() []*TopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetTopResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetTopResponse) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type TopItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TopItem) Reset() {
	*x = TopItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopItem) ProtoMessage() {}

func (x *TopItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopItem.ProtoReflect.Descriptor instead.
func (*TopItem) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{2}
}

func (x *TopItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TopItem) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StopWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *StopWordRequest) Reset() {
	*x = StopWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWordRequest) ProtoMessage() {}

func (x *StopWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWordRequest.ProtoReflect.Descriptor instead.
func (*StopWordRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{3}
}

func (x *StopWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type StopWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word    string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Applied bool   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StopWordResponse) Reset() {
	*x = StopWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWordResponse) ProtoMessage() {}

func (x *StopWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWordResponse.ProtoReflect.Descriptor instead.
func (*StopWordResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{4}
}

func (x *StopWordResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *StopWordResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *StopWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListStopWordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListStopWordsRequest) Reset() {
	*x = ListStopWordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStopWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopWordsRequest) ProtoMessage() {}

func (x *ListStopWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopWordsRequest.ProtoReflect.Descriptor instead.
func (*ListStopWordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{5}
}

type ListStopWordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *ListStopWordsResponse) Reset() {
	*x = ListStopWordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStopWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStopWordsResponse) ProtoMessage() {}

func (x *ListStopWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStopWordsResponse.ProtoReflect.Descriptor instead.
func (*ListStopWordsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{6}
}

func (x *ListStopWordsResponse) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CheckedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_trends_v1_search_trends_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_trends_v1_search_trends_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_proto_search_trends_v1_search_trends_proto protoreflect.FileDescriptor

var file_proto_search_trends_v1_search_trends_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74,
	0x72, 0x65, 0x6e, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0x35, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x57,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5a,
	0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x68, 0x0a, 0x13, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x41,
	0x74, 0x32, 0xcf, 0x03, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x72, 0x65, 0x6e,
	0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65,
	0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72,
	0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f,
	0x70, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74,
	0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x21,
	0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f,
	0x70, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x26, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74,
	0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x62, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2d, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73,
	0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_search_trends_v1_search_trends_proto_rawDescOnce sync.Once
	file_proto_search_trends_v1_search_trends_proto_rawDescData = file_proto_search_trends_v1_search_trends_proto_rawDesc
)

func file_proto_search_trends_v1_search_trends_proto_rawDescGZIP() []byte {
	file_proto_search_trends_v1_search_trends_proto_rawDescOnce.Do(func() {
		file_proto_search_trends_v1_search_trends_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_search_trends_v1_search_trends_proto_rawDescData)
	})
	return file_proto_search_trends_v1_search_trends_proto_rawDescData
}

var file_proto_search_trends_v1_search_trends_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_search_trends_v1_search_trends_proto_goTypes = []any{
	(*GetTopRequest)(nil),         // 0: search_trends.v1.GetTopRequest
	(*GetTopResponse)(nil),        // 1: search_trends.v1.GetTopResponse
	(*TopItem)(nil),               // 2: search_trends.v1.TopItem
	(*StopWordRequest)(nil),       // 3: search_trends.v1.StopWordRequest
	(*StopWordResponse)(nil),      // 4: search_trends.v1.StopWordResponse
	(*ListStopWordsRequest)(nil),  // 5: search_trends.v1.ListStopWordsRequest
	(*ListStopWordsResponse)(nil), // 6: search_trends.v1.ListStopWordsResponse
	(*HealthCheckRequest)(nil),    // 7: search_trends.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: search_trends.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_proto_search_trends_v1_search_trends_proto_depIdxs = []int32{
	2, // 0: search_trends.v1.GetTopResponse.items:type_name -> search_trends.v1.TopItem
	9, // 1: search_trends.v1.GetTopResponse.generated_at:type_name -> google.protobuf.Timestamp
	9, // 2: search_trends.v1.HealthCheckResponse.checked_at:type_name -> google.protobuf.Timestamp
	0, // 3: search_trends.v1.SearchTrendsService.GetTop:input_type -> search_trends.v1.GetTopRequest
	3, // 4: search_trends.v1.SearchTrendsService.AddStopWord:input_type -> search_trends.v1.StopWordRequest
	3, // 5: search_trends.v1.SearchTrendsService.RemoveStopWord:input_type -> search_trends.v1.StopWordRequest
	5, // 6: search_trends.v1.SearchTrendsService.ListStopWords:input_type -> search_trends.v1.ListStopWordsRequest
	7, // 7: search_trends.v1.SearchTrendsService.HealthCheck:input_type -> search_trends.v1.HealthCheckRequest
	1, // 8: search_trends.v1.SearchTrendsService.GetTop:output_type -> search_trends.v1.GetTopResponse
	4, // 9: search_trends.v1.SearchTrendsService.AddStopWord:output_type -> search_trends.v1.StopWordResponse
	4, // 10: search_trends.v1.SearchTrendsService.RemoveStopWord:output_type -> search_trends.v1.StopWordResponse
	6, // 11: search_trends.v1.SearchTrendsService.ListStopWords:output_type -> search_trends.v1.ListStopWordsResponse
	8, // 12: search_trends.v1.SearchTrendsService.HealthCheck:output_type -> search_trends.v1.HealthCheckResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_search_trends_v1_search_trends_proto_init() }
func file_proto_search_trends_v1_search_trends_proto_init() {
	if File_proto_search_trends_v1_search_trends_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_search_trends_v1_search_trends_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TopItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StopWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StopWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListStopWordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListStopWordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_trends_v1_search_trends_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*HealthCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_search_trends_v1_search_trends_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_trends_v1_search_trends_proto_goTypes,
		DependencyIndexes: file_proto_search_trends_v1_search_trends_proto_depIdxs,
		MessageInfos:      file_proto_search_trends_v1_search_trends_proto_msgTypes,
	}.Build()
	File_proto_search_trends_v1_search_trends_proto = out.File
	file_proto_search_trends_v1_search_trends_proto_rawDesc = nil
	file_proto_search_trends_v1_search_trends_proto_goTypes = nil
	file_proto_search_trends_v1_search_trends_proto_depIdxs = nil
}
